export const EXPENSE_REQUEST = "EXPENSE_REQUEST";
export const EXPENSE_SUCESS = "EXPENSE_SUCESS";
export const EXPENSE_FAIL = "EXPENSE_FAIL";

export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST";
export const ADD_EXPENSE_SUCESS = "ADD_EXPENSE_SUCESS";
export const ADD_EXPENSE_FAIL = "ADD_EXPENSE_FAIL";

export const DELETE_EXPENSE_REQUEST = "DELETE_EXPENSE_REQUEST";
export const DELETE_EXPENSE_SUCESS = "DELETE_EXPENSE_SUCESS";
export const DELETE_EXPENSE_FAIL = "DELETE_EXPENSE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
