export const INCOME_REQUEST = "INCOME_REQUEST";
export const INCOME_SUCESS = "INCOME_SUCESS";
export const INCOME_FAIL = "INCOME_FAIL";

export const ADD_INCOME_REQUEST = "ADD_INCOME_REQUEST";
export const ADD_INCOME_SUCESS = "ADD_INCOME_SUCESS";
export const ADD_INCOME_FAIL = "ADD_INCOME_FAIL";

export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const DELETE_INCOME_SUCESS = "DELETE_INCOME_SUCESS";
export const DELETE_INCOME_FAIL = "DELETE_INCOME_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
